name: 'Publish Snapshot'
description: 'Publish snapshot artifacts and latest API doc.'

runs:
  using: "composite"
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'zulu'
        server-id: google-snapshots
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: 'Cache local Maven repository'
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Publish Javadoc
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        chmod +x util/publish-latest-docs.sh
        ./util/publish-latest-docs.sh
      shell: bash
    - name: Publish Snapshot
      run: mvn clean deploy -DskipTests=true -Dmaven.javadoc.skip=true
      shell: bash
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}