# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: continuous-integration
env:
  USE_BAZEL_VERSION: '4.2.2'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  # On main branch, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ (github.ref == 'refs/heads/master') && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8, 11, 15, 17]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/maven-test

  bazel-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8, 11, 15, 17]
      fail-fast: false
      max-parallel: 4
    name: Bazel Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bazel-test

  publish:
    runs-on: ubuntu-latest
    needs: [test, bazel-test]
    if: github.event_name == 'push' && github.repository == 'google/guice' && github.ref == 'refs/heads/master'
    name: Publish Javadoc and Snapshot

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/publish-snapshot